std_msgs/Empty  Empty
---
float64 x_r		#World coords w.r.t. map  poiting with right hand
float64 y_r
float64 z_r

float64 x_l		#World coords w.r.t. map  pointing  with left hand
float64 y_l
float64 z_l
sensor_msgs/Image[] debug_image
