(cl:defpackage conceptual_deps-srv
  (:use )
  (:export
   "GETCONDEP"
   "<GETCONDEP-REQUEST>"
   "GETCONDEP-REQUEST"
   "<GETCONDEP-RESPONSE>"
   "GETCONDEP-RESPONSE"
   "GETTEXTCONDEP"
   "<GETTEXTCONDEP-REQUEST>"
   "GETTEXTCONDEP-REQUEST"
   "<GETTEXTCONDEP-RESPONSE>"
   "GETTEXTCONDEP-RESPONSE"
  ))

