// Generated by gencpp from file conceptual_deps/GetConDepRequest.msg
// DO NOT EDIT!


#ifndef CONCEPTUAL_DEPS_MESSAGE_GETCONDEPREQUEST_H
#define CONCEPTUAL_DEPS_MESSAGE_GETCONDEPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conceptual_deps
{
template <class ContainerAllocator>
struct GetConDepRequest_
{
  typedef GetConDepRequest_<ContainerAllocator> Type;

  GetConDepRequest_()
    {
    }
  GetConDepRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetConDepRequest_

typedef ::conceptual_deps::GetConDepRequest_<std::allocator<void> > GetConDepRequest;

typedef boost::shared_ptr< ::conceptual_deps::GetConDepRequest > GetConDepRequestPtr;
typedef boost::shared_ptr< ::conceptual_deps::GetConDepRequest const> GetConDepRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conceptual_deps::GetConDepRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace conceptual_deps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::conceptual_deps::GetConDepRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conceptual_deps/GetConDepRequest";
  }

  static const char* value(const ::conceptual_deps::GetConDepRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::conceptual_deps::GetConDepRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetConDepRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conceptual_deps::GetConDepRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::conceptual_deps::GetConDepRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CONCEPTUAL_DEPS_MESSAGE_GETCONDEPREQUEST_H
