// Generated by gencpp from file conceptual_deps/GetConDep.msg
// DO NOT EDIT!


#ifndef CONCEPTUAL_DEPS_MESSAGE_GETCONDEP_H
#define CONCEPTUAL_DEPS_MESSAGE_GETCONDEP_H

#include <ros/service_traits.h>


#include <conceptual_deps/GetConDepRequest.h>
#include <conceptual_deps/GetConDepResponse.h>


namespace conceptual_deps
{

struct GetConDep
{

typedef GetConDepRequest Request;
typedef GetConDepResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetConDep
} // namespace conceptual_deps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::conceptual_deps::GetConDep > {
  static const char* value()
  {
    return "6530474bcb00416881ea95591006435a";
  }

  static const char* value(const ::conceptual_deps::GetConDep&) { return value(); }
};

template<>
struct DataType< ::conceptual_deps::GetConDep > {
  static const char* value()
  {
    return "conceptual_deps/GetConDep";
  }

  static const char* value(const ::conceptual_deps::GetConDep&) { return value(); }
};


// service_traits::MD5Sum< ::conceptual_deps::GetConDepRequest> should match
// service_traits::MD5Sum< ::conceptual_deps::GetConDep >
template<>
struct MD5Sum< ::conceptual_deps::GetConDepRequest>
{
  static const char* value()
  {
    return MD5Sum< ::conceptual_deps::GetConDep >::value();
  }
  static const char* value(const ::conceptual_deps::GetConDepRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::conceptual_deps::GetConDepRequest> should match
// service_traits::DataType< ::conceptual_deps::GetConDep >
template<>
struct DataType< ::conceptual_deps::GetConDepRequest>
{
  static const char* value()
  {
    return DataType< ::conceptual_deps::GetConDep >::value();
  }
  static const char* value(const ::conceptual_deps::GetConDepRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::conceptual_deps::GetConDepResponse> should match
// service_traits::MD5Sum< ::conceptual_deps::GetConDep >
template<>
struct MD5Sum< ::conceptual_deps::GetConDepResponse>
{
  static const char* value()
  {
    return MD5Sum< ::conceptual_deps::GetConDep >::value();
  }
  static const char* value(const ::conceptual_deps::GetConDepResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::conceptual_deps::GetConDepResponse> should match
// service_traits::DataType< ::conceptual_deps::GetConDep >
template<>
struct DataType< ::conceptual_deps::GetConDepResponse>
{
  static const char* value()
  {
    return DataType< ::conceptual_deps::GetConDep >::value();
  }
  static const char* value(const ::conceptual_deps::GetConDepResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONCEPTUAL_DEPS_MESSAGE_GETCONDEP_H
