// Generated by gencpp from file conceptual_deps/GetTextConDepResponse.msg
// DO NOT EDIT!


#ifndef CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEPRESPONSE_H
#define CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <conceptual_deps/StringArray.h>

namespace conceptual_deps
{
template <class ContainerAllocator>
struct GetTextConDepResponse_
{
  typedef GetTextConDepResponse_<ContainerAllocator> Type;

  GetTextConDepResponse_()
    : cds()  {
    }
  GetTextConDepResponse_(const ContainerAllocator& _alloc)
    : cds(_alloc)  {
  (void)_alloc;
    }



   typedef  ::conceptual_deps::StringArray_<ContainerAllocator>  _cds_type;
  _cds_type cds;





  typedef boost::shared_ptr< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTextConDepResponse_

typedef ::conceptual_deps::GetTextConDepResponse_<std::allocator<void> > GetTextConDepResponse;

typedef boost::shared_ptr< ::conceptual_deps::GetTextConDepResponse > GetTextConDepResponsePtr;
typedef boost::shared_ptr< ::conceptual_deps::GetTextConDepResponse const> GetTextConDepResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator1> & lhs, const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cds == rhs.cds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator1> & lhs, const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conceptual_deps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6530474bcb00416881ea95591006435a";
  }

  static const char* value(const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6530474bcb004168ULL;
  static const uint64_t static_value2 = 0x81ea95591006435aULL;
};

template<class ContainerAllocator>
struct DataType< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conceptual_deps/GetTextConDepResponse";
  }

  static const char* value(const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "StringArray  cds\n"
"\n"
"\n"
"================================================================================\n"
"MSG: conceptual_deps/StringArray\n"
"string[]  data\n"
;
  }

  static const char* value(const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTextConDepResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conceptual_deps::GetTextConDepResponse_<ContainerAllocator>& v)
  {
    s << indent << "cds: ";
    s << std::endl;
    Printer< ::conceptual_deps::StringArray_<ContainerAllocator> >::stream(s, indent + "  ", v.cds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEPRESPONSE_H
