// Generated by gencpp from file conceptual_deps/GetTextConDepRequest.msg
// DO NOT EDIT!


#ifndef CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEPREQUEST_H
#define CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conceptual_deps
{
template <class ContainerAllocator>
struct GetTextConDepRequest_
{
  typedef GetTextConDepRequest_<ContainerAllocator> Type;

  GetTextConDepRequest_()
    : text()  {
    }
  GetTextConDepRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTextConDepRequest_

typedef ::conceptual_deps::GetTextConDepRequest_<std::allocator<void> > GetTextConDepRequest;

typedef boost::shared_ptr< ::conceptual_deps::GetTextConDepRequest > GetTextConDepRequestPtr;
typedef boost::shared_ptr< ::conceptual_deps::GetTextConDepRequest const> GetTextConDepRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator1> & lhs, const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator1> & lhs, const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conceptual_deps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conceptual_deps/GetTextConDepRequest";
  }

  static const char* value(const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
;
  }

  static const char* value(const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTextConDepRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conceptual_deps::GetTextConDepRequest_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEPREQUEST_H
