// Generated by gencpp from file conceptual_deps/GetTextConDep.msg
// DO NOT EDIT!


#ifndef CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEP_H
#define CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEP_H

#include <ros/service_traits.h>


#include <conceptual_deps/GetTextConDepRequest.h>
#include <conceptual_deps/GetTextConDepResponse.h>


namespace conceptual_deps
{

struct GetTextConDep
{

typedef GetTextConDepRequest Request;
typedef GetTextConDepResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTextConDep
} // namespace conceptual_deps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::conceptual_deps::GetTextConDep > {
  static const char* value()
  {
    return "b7e9f26875b56c920fd22b0d43671c0b";
  }

  static const char* value(const ::conceptual_deps::GetTextConDep&) { return value(); }
};

template<>
struct DataType< ::conceptual_deps::GetTextConDep > {
  static const char* value()
  {
    return "conceptual_deps/GetTextConDep";
  }

  static const char* value(const ::conceptual_deps::GetTextConDep&) { return value(); }
};


// service_traits::MD5Sum< ::conceptual_deps::GetTextConDepRequest> should match
// service_traits::MD5Sum< ::conceptual_deps::GetTextConDep >
template<>
struct MD5Sum< ::conceptual_deps::GetTextConDepRequest>
{
  static const char* value()
  {
    return MD5Sum< ::conceptual_deps::GetTextConDep >::value();
  }
  static const char* value(const ::conceptual_deps::GetTextConDepRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::conceptual_deps::GetTextConDepRequest> should match
// service_traits::DataType< ::conceptual_deps::GetTextConDep >
template<>
struct DataType< ::conceptual_deps::GetTextConDepRequest>
{
  static const char* value()
  {
    return DataType< ::conceptual_deps::GetTextConDep >::value();
  }
  static const char* value(const ::conceptual_deps::GetTextConDepRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::conceptual_deps::GetTextConDepResponse> should match
// service_traits::MD5Sum< ::conceptual_deps::GetTextConDep >
template<>
struct MD5Sum< ::conceptual_deps::GetTextConDepResponse>
{
  static const char* value()
  {
    return MD5Sum< ::conceptual_deps::GetTextConDep >::value();
  }
  static const char* value(const ::conceptual_deps::GetTextConDepResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::conceptual_deps::GetTextConDepResponse> should match
// service_traits::DataType< ::conceptual_deps::GetTextConDep >
template<>
struct DataType< ::conceptual_deps::GetTextConDepResponse>
{
  static const char* value()
  {
    return DataType< ::conceptual_deps::GetTextConDep >::value();
  }
  static const char* value(const ::conceptual_deps::GetTextConDepResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONCEPTUAL_DEPS_MESSAGE_GETTEXTCONDEP_H
