// Generated by gencpp from file conceptual_deps/StringArray.msg
// DO NOT EDIT!


#ifndef CONCEPTUAL_DEPS_MESSAGE_STRINGARRAY_H
#define CONCEPTUAL_DEPS_MESSAGE_STRINGARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conceptual_deps
{
template <class ContainerAllocator>
struct StringArray_
{
  typedef StringArray_<ContainerAllocator> Type;

  StringArray_()
    : data()  {
    }
  StringArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::conceptual_deps::StringArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conceptual_deps::StringArray_<ContainerAllocator> const> ConstPtr;

}; // struct StringArray_

typedef ::conceptual_deps::StringArray_<std::allocator<void> > StringArray;

typedef boost::shared_ptr< ::conceptual_deps::StringArray > StringArrayPtr;
typedef boost::shared_ptr< ::conceptual_deps::StringArray const> StringArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conceptual_deps::StringArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conceptual_deps::StringArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conceptual_deps::StringArray_<ContainerAllocator1> & lhs, const ::conceptual_deps::StringArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conceptual_deps::StringArray_<ContainerAllocator1> & lhs, const ::conceptual_deps::StringArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conceptual_deps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conceptual_deps::StringArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conceptual_deps::StringArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conceptual_deps::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conceptual_deps::StringArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conceptual_deps::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conceptual_deps::StringArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conceptual_deps::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cce5a364f3a3be12c9722c6dcad2fa94";
  }

  static const char* value(const ::conceptual_deps::StringArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcce5a364f3a3be12ULL;
  static const uint64_t static_value2 = 0xc9722c6dcad2fa94ULL;
};

template<class ContainerAllocator>
struct DataType< ::conceptual_deps::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conceptual_deps/StringArray";
  }

  static const char* value(const ::conceptual_deps::StringArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conceptual_deps::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[]  data\n"
;
  }

  static const char* value(const ::conceptual_deps::StringArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conceptual_deps::StringArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conceptual_deps::StringArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conceptual_deps::StringArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONCEPTUAL_DEPS_MESSAGE_STRINGARRAY_H
