// Generated by gencpp from file robotino_msgs/ResetOdometryRequest.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_RESETODOMETRYREQUEST_H
#define ROBOTINO_MSGS_MESSAGE_RESETODOMETRYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotino_msgs
{
template <class ContainerAllocator>
struct ResetOdometryRequest_
{
  typedef ResetOdometryRequest_<ContainerAllocator> Type;

  ResetOdometryRequest_()
    : x(0.0)
    , y(0.0)
    , phi(0.0)  {
    }
  ResetOdometryRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , phi(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _phi_type;
  _phi_type phi;





  typedef boost::shared_ptr< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetOdometryRequest_

typedef ::robotino_msgs::ResetOdometryRequest_<std::allocator<void> > ResetOdometryRequest;

typedef boost::shared_ptr< ::robotino_msgs::ResetOdometryRequest > ResetOdometryRequestPtr;
typedef boost::shared_ptr< ::robotino_msgs::ResetOdometryRequest const> ResetOdometryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator1> & lhs, const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.phi == rhs.phi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator1> & lhs, const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotino_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "400210218ff66e5bce9e5be16653c0c8";
  }

  static const char* value(const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x400210218ff66e5bULL;
  static const uint64_t static_value2 = 0xce9e5be16653c0c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_msgs/ResetOdometryRequest";
  }

  static const char* value(const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x # in meters\n"
"float32 y # in meters\n"
"float32 phi # in rad\n"
;
  }

  static const char* value(const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.phi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetOdometryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_msgs::ResetOdometryRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "phi: ";
    Printer<float>::stream(s, indent + "  ", v.phi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_RESETODOMETRYREQUEST_H
